version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5436:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

  # metabase:
  #   image: metabase/metabase
  #   ports:
  #     - "3000:3000"

  # adminer:
  #   image: adminer
  #   ports:
  #     - "8080:8080"