[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
program2 = "7RXoiLFXMpXsAcWmgL877y54V8TtkSGorSA6wjv2gy8w"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test1 = "anchor test --skip-local-validator"
my-custom-script = "echo 'Hello world!'"
test2 = "anchor build && anchor deploy && anchor test --skip-local-validator"
test3 = "solana-test-validator --reset && anchor build && anchor deploy && anchor run test --skip-local-validator"