[programs.localnet]
solana_voting = "9UTX1Zk1tXzNxyWz813HTSkKkqyNFVuH4gawMZK1EwAy"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/maarunipandithurai/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
my-custom-script = "echo 'Hello world!'"
test2 = "anchor build && anchor deploy && anchor test"
test3 = "solana-test-validator --no-bpf-jit --reset && anchor build && anchor deploy && anchor run test"